# -*- coding: utf-8 -*-
"""TrabalhoML_PedroeGustavo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eM9-c1rEOkKEahnCnQypvigo1E9AghQ6

# **Importação de bibliotecas e carga dos dados**
"""

#Importação das bibliotecas
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn import tree
import pickle

#Carregar os dados
csv_url = 'https://docs.google.com/spreadsheets/d/1bjwxd2sC4gmYDu7HCbEF3DU4fDWi_J0voXXZ8I59aFI/export?format=csv&id=1bjwxd2sC4gmYDu7HCbEF3DU4fDWi_J0voXXZ8I59aFI'
df = pd.read_csv(csv_url)

#Verificar a distribuição das classes
print("Distribuição das classes:")
print(df['categoria_animal'].value_counts())

"""# **Mapeamento das classes e preparação dos dados**"""

#Mapeamento das classes
class_mapping = {
    "Mamífero": 1,
    "Ave": 2,
    "Réptil": 3,
    "Peixe": 4,
    "Anfíbio": 5,
    "Inseto": 6,
    "Invertebrado": 7
}

#Adicionar a coluna codificada
df['categoria_animal_cod'] = df['categoria_animal'].map(class_mapping)

#Separar as colunas de entrada (features) e a coluna alvo
X = df.drop(columns=['categoria_animal', 'categoria_animal_cod'])
y = df['categoria_animal_cod']

#Divisão dos dados em treino e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=50)

#Ajustar pesos das classes para lidar com o desequilíbrio
class_weights = {1: 1, 2: 1, 3: 1, 4: 1, 5: 2, 6: 2, 7: 2}  # Classes 5, 6 e 7 têm mais peso

#Treinando o classificador com pesos das classes
clf = tree.DecisionTreeClassifier(max_depth=5, min_samples_split=10, class_weight=class_weights)
clf = clf.fit(X_train, y_train)

#Prevendo e avaliando a acurácia
y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Acurácia do modelo: {accuracy}")

#Salvando o modelo e os mapeamentos
pickle.dump(clf, open('model.pkl', 'wb'))
pickle.dump(class_mapping, open('names.pkl', 'wb'))

#Função para obter dados de entrada
def obter_dados_entrada():
    try:
        pelos = int(input("O animal tem pelos? (1 para sim, 0 para não): "))
        penas = int(input("O animal tem penas? (1 para sim, 0 para não): "))
        oviparo = int(input("O animal é ovíparo? (1 para sim, 0 para não): "))
        voador = int(input("O animal é voador? (1 para sim, 0 para não): "))
        aquático = int(input("O animal é aquático? (1 para sim, 0 para não): "))
        predador = int(input("O animal é predador? (1 para sim, 0 para não): "))
        com_dentes = int(input("O animal tem dentes? (1 para sim, 0 para não): "))
        coluna_vertebral = int(input("O animal tem coluna vertebral? (1 para sim, 0 para não): "))
        respira = int(input("O animal respira? (1 para sim, 0 para não): "))
        venenoso = int(input("O animal é venenoso? (1 para sim, 0 para não): "))
        barbatanas = int(input("O animal tem barbatanas? (1 para sim, 0 para não): "))
        pernas = int(input("Quantas pernas o animal tem? (Digite 0, 2, 4, 6...): "))
        cauda = int(input("O animal tem cauda? (1 para sim, 0 para não): "))
        domestico = int(input("O animal é doméstico? (1 para sim, 0 para não): "))

        return [[pelos, penas, oviparo, voador, aquático, predador, com_dentes, coluna_vertebral, respira, venenoso, barbatanas, pernas, cauda, domestico]]
    except ValueError:
        print("Por favor, insira valores numéricos válidos.")
        return None

#Obter a entrada e fazer a previsão
entrada = obter_dados_entrada()
if entrada is not None and len(entrada) > 0:  # Verifica se a entrada é válida
    predito = clf.predict(entrada)
    categorias = pickle.load(open('names.pkl', 'rb'))
    categoria_prevista = [k for k, v in categorias.items() if v == predito[0]][0]
    print("Categoria prevista:", categoria_prevista)
else:
    print("Entrada inválida.")